---
- name: Install and Configure Apache on Localhost
  hosts: localhost
  become: yes  # This ensures the tasks are run with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 service is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Allow HTTP traffic through UFW (if UFW is active)
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
        comment: Allow HTTP
      ignore_errors: yes # Ignore if UFW is not installed or enabled
